/* repmisc.c */
Float AgeOf(Ts *ts, Obj *obj);
Bool IsOwnerOf(Ts *ts, TsRange *tsr, Obj *object, Obj *owner);
Obj *GuardianOf(Ts *ts, TsRange *tsr, Obj *human);
Bool GetActorPair1(Obj *con, Obj *actor, int i, Obj **counter_actor);
Bool GetActorPair(Obj *con, Obj *actor, Obj **counter_actor);
Bool GetSpatial(Obj *con, Obj **from, Obj **to);
Bool GetActorSpatial(Obj *con, Obj *actor, Obj **from, Obj **to);
Dur DurationOf(Obj *action);
Dur DurValueOf(Obj *obj);
Float FloatValueOf(Obj *obj);
Float FloatMinValueOf(Obj *obj);
Float FloatMaxValueOf(Obj *obj);
Bool FloatIsInRange(Float x, Obj *obj);
Dur DurCanonicalFactorOf(Obj *obj);
Float FloatCanonicalFactorOf(Obj *obj);
Float RoughSizeOf(Ts *ts, Obj *obj);
Obj *GoalObjectiveOf(Obj *goal);
Obj *GoalCreate(Obj *goal_status, Obj *actor, Obj *objective);
Dur HumanPunctuality(Obj *human, Obj *appointment);
Dur HumanWaitLimit(Obj *human, Obj *appointment);
Bool IsGarbage(Obj *obj);
Bool NotNA(Obj *obj);
void LEADTO(Ts *ts, Obj *cause, Obj *result);
ObjList *CAUSES(Obj *result, Context *cx);
ObjList *RESULTS(Obj *cause, Context *cx);
Obj *SexOpposite(Obj *sex);
int SexToFeat(Obj *sex);
Bool IsInterrogative(Obj *obj);
Bool IsActor(Obj *obj);
Obj *ThereAreXClass(Float count, Obj *class);
Obj *ActorGet(Obj *obj);
