/* tatime.c */
int TimeFixYear(int year);
Bool TA_TimeHHMM1(char *s, Tod *tod);
Bool TA_TimeHHMMSS1(char *s, Tod *tod);
Bool TA_TimeHHMMPX(char *s, Tod *tod);
Bool TA_TimeMMDDYYX(char *s, Ts *ts);
Bool TA_TimeDOSDateTime(char *s, Ts *ts);
Bool TA_TimeHHMMX(char *s, Tod *tod);
Bool TA_TimeMini(char *sent, Ts *ts, char **nextp);
Bool TA_TimeUnixEtc(char *sent, Ts *ts, char **nextp);
Bool TA_TimeMonthnum1(char *word, int *month);
Bool TA_TimeYear1(char *word, int *year);
Bool TA_TimeYear3(char *word, int *year);
Bool TA_TimeYear4(char *word, int *year);
Bool TA_TimeYear(char *sent, int *year, char **nextp);
Bool TA_TimeDay1(char *word, int *day);
Bool TA_TimeDay(char *sent, int *day, char **nextp);
Bool TA_TimeDayOfWeek1(char *word, int *day_of_the_week);
Bool TA_TimeDayOfWeek(char *sent, int *day_of_the_week, char **nextp);
Bool TA_TimeMonth1(char *word, int *month);
Bool TA_TimeMonth(char *sent, int *month, char **nextp);
Bool TA_TimeTimezone1(char *word, int *timezone);
Bool TA_TimeTimezone(char *sent, int *timezone, char **nextp);
Bool TA_Time_Date(char *sent, HashTable *ht, Ts *ts, char **nextp);
Bool PNodeTypeClassMatch(PNode *pn, int typ, Obj *class, Obj **obj_out);
int PNodeApplyRule(PNode *pns, size_t startpos, int *lhs_types, Obj **lhs_classes, int len, PNode **pns_out, Obj **objs_out, size_t *stoppos);
Bool PNodeInArray(PNode *pn, PNode **pns, int len);
void PNodeEliminateLHSNodes(PNodeList *pnf, PNode **elim_pns, int len);
Bool TA_Time_Abouts(PNode *pns, size_t startpos, Discourse *dc, Channel *ch);
Bool TA_Time_MergeDateTod(PNode *pns, size_t startpos, Discourse *dc, Channel *ch);
Bool TA_Time_Combinations(PNode *pns, size_t startpos, Discourse *dc, Channel *ch);
Bool TA_Time_Dur(PNode *pns, size_t startpos, Discourse *dc, Channel *ch);
Float AdverbHourOfDayToOffset(Obj *adv);
Bool TA_Time_Tod(PNode *pns, size_t startpos, Discourse *dc, Channel *ch, size_t *stoppos_r);
Bool TA_RelativeDayAndPartOfTheDay(char *sent, HashTable *ht, Discourse *dc, TsRange *tsr, char **nextp);
Bool TA_TimeTsRange(char *sent, HashTable *ht, TsRange *tsr, char **nextp);
Bool TA_TsRange(char *in, Discourse *dc, Channel *ch, char **nextp);
