/* uadict.c */
ObjList *DictRelationsAndCounts(Ts *ts, TsRange *tsr, Obj *obj, int i, ObjList *rels_and_counts, ObjList *assertions, ObjList **assertions_p);
ObjList *DictFrequentRels(Ts *ts, TsRange *tsr, ObjList *objs, int i, ObjList **assertions_p);
void DictPrintRelValues(Rpt *rpt, TsRange *tsr, ObjList *assertions, Obj *obj, Obj *rel, int i, Discourse *dc, char *buf1);
Rpt *DictTableObjByValue1(ObjList *assertions, ObjList *objs, Obj *obj, Obj *rel, int i, Discourse *dc);
void DictTableObjByValue(Text *text, Ts *ts, TsRange *tsr, Obj *obj, ObjList *objs, Discourse *dc);
Rpt *DictTableTsRangeByValue1(ObjList *assertions, Obj *rel, int i, Discourse *dc);
void DictTableTsRangeByValue(Text *text, TsRange *tsr, Obj *obj, Discourse *dc);
void DictObjTables(Text *text, Obj *obj, Discourse *dc);
Bool DictOle(int html, Obj *type, Text *text, ObjToLexEntry *ole, int post, int orig_pos, int pos, int lang, Discourse *dc);
Bool DictRelatedWords2(int html, Obj *type, Text *text, Obj *obj, int orig_pos, int pos, int dialect, int freq, int lang, LexEntry *le, Discourse *dc);
Bool DictRelatedWords1(int html, Obj *type, Text *text, Obj *obj, int orig_pos, LexEntry *le, ABrainTask *abt, Discourse *dc);
Bool DictRelatedWords(int html, Text *text, Obj *obj, int orig_pos, LexEntry *le, ABrainTask *abt, Discourse *dc);
void DictChildren(Text *text, int objtype, Obj *type, Obj *parent, Obj *except, int orig_pos, Discourse *dc);
void DictContrastParent1(Text *text, Obj *obj, Obj *parent, Obj *grandparent, int orig_pos, LexEntry *le, Discourse *dc);
void DictContrastParent(Text *text, Obj *obj, Obj *parent, int orig_pos, LexEntry *le, Discourse *dc);
void DictObjList(Text *text, PNode *header, ObjList *objs, Obj *except, Obj *article, int pos, int paruniv, int post, int maxlen, Discourse *dc);
void DictAbstractParent(Text *text, Obj *obj, Obj *parent, int orig_pos, LexEntry *le, int describe_children, Discourse *dc);
void DictDbFile1(Text *text, Obj *obj, Obj *parent, int orig_pos, LexEntry *le, int first, Discourse *dc);
void DictDbFile(Text *text, Obj *obj, int orig_pos, LexEntry *le, Discourse *dc);
void DictAssocAssertion(Text *text, Obj *obj, Discourse *dc, int free_ok);
void DictAssocObject(Text *text, Obj *obj, Discourse *dc);
void DictHuman(Text *text, Ts *ts, TsRange *tsr, Obj *human, Discourse *dc);
void DictInvolving(Text *text, Obj *obj, Discourse *dc);
void DictObj(Text *text, Obj *obj, int orig_pos, LexEntry *le, Discourse *dc);
void DictInfl(Text *text, Word *infl, Discourse *dc);
ObjList *DictLexEntry(Text *text, LexEntry *le, int showinfl, ObjList *objs, Discourse *dc);
ObjList *DictPhrase2(Text *text, int pos, char *phrase, HashTable *ht, int showinfl, ObjList *objs, char *lenum, Discourse *dc);
ObjList *DictPhrase1(Text *text, char *phrase, HashTable *ht, int showinfl, ObjList *objs, char *lenum, Discourse *dc);
void DictPhrase(Text *text, char *phrase, int showinfl, Discourse *dc);
void Dictionary(void);
void Dictionary1(char *phrase, int showinfl, Discourse *dc);
