/* utillrn.c */
void LearnFileAdd(char *fn, Obj *class);
LearnFile *LearnFileFindCatchall(void);
LearnFile *LearnFileFindClass(Obj *class);
LearnFile *LearnFileFindObj(Obj *obj);
LearnFile *LearnFileFindAssertion(Obj *assertion);
void LearnInit(void);
void LearnClose(void);
void LearnAnnotate(LearnFile *lf, Discourse *dc, char *input_text);
void LearnCommentary_I_Know(Context *cx, Obj *existing);
void LearnCommentary_I_Did_Not_Know(Context *cx, Obj *not_known);
void LearnCommentary_I_Thought(Context *cx, Obj *existing, int gen_ts);
void LearnCommentary_Specification(Context *cx, Obj *existing, Obj *new, int gen_ts);
void LearnObjLeUPDATE(char *le_text, char *features, Obj *obj);
void LearnNameLeUPDATE(Name *nm, int gender, Obj *human);
int LearnFileCloseAssertion(LearnFile *lf);
void LearnObjDUMP(Obj *parent, Obj *obj, char *le, char *feat1, char *feat2, int is_le0, int create_flag, char *input_text, Discourse *dc);
void LearnAssertDUMP(Obj *obj, Discourse *dc);
void LearnAssert(Obj *obj, Discourse *dc);
void LearnAssertTs(Ts *ts, Obj *obj, Discourse *dc);
void LearnAssertDest(Obj *obj, Discourse *dc);
void LearnRetract(Ts *ts, Obj *obj, Discourse *dc);
void LearnObj(Obj *parent, Obj *obj, char *le, char *feat1, char *feat2, int is_le0, int create_flag, char *input_text, Discourse *dc);
void LearnObjClass(Obj *obj, Obj *was_class, Obj *is_class);
Obj *LearnName(char *name, Obj *class, int gender, char *input_text, Discourse *dc);
void LearnNewNames(int gender);
Obj *LearnObjText(Obj *parent, char *text, int gender, int number, int pos, int lang, int existing_ok, int create_flag, char *input_text, Discourse *dc);
Obj *LearnObjToken(Obj *parent, char *text, char *input_text, Discourse *dc);
void LearnHumanGetInfo(ObjList *human_names, Obj **sex, Obj **nationality, ObjList **sex_just, ObjList **nation_just);
Obj *LearnHuman(Name *nm, char *input_text, Discourse *dc, int *gender);
