/* utilhtml.c */
void HTML_BeginDocument(FILE *stream, char *title);
void HTML_EndDocument(FILE *stream);
void HTML_LineBreak(FILE *stream);
void HTML_BlankPage(FILE *stream);
void HTML_NewParagraph(FILE *stream);
void HTML_TextNewParagraph(Text *text);
void HTML_HorizontalRule(FILE *stream);
void HTML_Print(FILE *stream, char *s);
void HTML_TextPrint(Text *text, char *s);
void HTML_StringPrint(char *s, char *out);
void HTML_TextPrintBoldBeginIfEnglish(Text *text, int lang);
void HTML_TextPrintBoldEndIfEnglish(Text *text, int lang);
void HTML_PrintBoldBeginIfEnglish(FILE *stream, int lang);
void HTML_PrintBoldEndIfEnglish(FILE *stream, int lang);
void HTML_PrintBold(FILE *stream, char *s);
void HTML_TextPrintBold(Text *text, char *s);
void HTML_PrintItalic(FILE *stream, char *s);
void HTML_PrintTypewriter(FILE *stream, char *s);
void HTML_TextPrintTypewriter(Text *text, char *s);
void HTML_PrintH1(FILE *stream, char *s);
void HTML_PrintH2(FILE *stream, char *s);
void HTML_PrintH2Begin(FILE *stream);
void HTML_PrintH2End(FILE *stream);
void HTML_BeginUnnumberedList(FILE *stream);
void HTML_TextBeginUnnumberedList(Text *text);
void HTML_UnnumberedListElement(FILE *stream);
void HTML_TextUnnumberedListElement(Text *text);
void HTML_EndUnnumberedList(FILE *stream);
void HTML_TextEndUnnumberedList(Text *text);
void HTML_BeginDefinitionList(FILE *stream);
void HTML_DefinitionListElementTitle(FILE *stream);
void HTML_DefinitionListElementDef(FILE *stream);
void HTML_EndDefinitionList(FILE *stream);
void HTML_TextObjName(Text *text, Obj *obj, int objname, int english, int french);
void HTML_ObjName(FILE *stream, Obj *obj, int objname, int english, int french);
void HTML_StringObjName(Obj *obj, int objname, int english, int french, char *out);
void HTML_LEName(FILE *stream, LexEntry *le, char *word);
int HTML_Hash(char *name, int hashsize);
void HTML_StringObjFilename(Obj *obj, char *out);
void HTML_TextObjFilename(Text *text, Obj *obj);
void HTML_LEHrefString(LexEntry *le, char *out);
void HTML_StringLinkToLE(LexEntry *le, char *out);
void HTML_ObjTargetLocation(FILE *stream, Obj *obj, int objname, int english, int french);
void HTML_LETargetLocation(FILE *stream, LexEntry *le);
void HTML_StringLinkToObj(Obj *obj, int objname, int english, int french, char *out);
void HTML_LinkToObj(FILE *stream, Obj *obj, int objname, int english, int french);
void HTML_TextLinkToObj(Text *text, Obj *obj, int objname, int english, int french);
void HTML_LinkTo(FILE *stream, char *name);
void TT_HTML(int objname, int english, int french);
void TT_HTML_Init(void);
void TT_HTML_LE(int objname, int english, int french);
void TT_HTML_LE1(int hashi, StringArray *index_sa, int objname, int english, int french);
void TT_HTML_LEDump(FILE *stream, StringArray *index_sa, LexEntry *le, int objname, int english, int french);
void TT_HTML_LEDumpInfl(FILE *stream, LexEntry *le);
void TT_HTML_Obj(int objname, int english, int french);
void TT_HTML_Obj1(int hashi, int objname, int english, int french);
void TT_HTML_ObjAssertions(FILE *stream, Obj *obj, int i, int objname, int english, int french, int *first);
void TT_HTML_ObjRelationValues(FILE *stream, char *title, Obj *prop, Obj *obj, int i, int objname, int english, int french);
void TT_HTML_ObjDump(FILE *stream, Obj *obj, int objname, int english, int french);
